my_string = input("Введите строку: \n")
# print("Введено ", my_string.__len__(), " символов.")
print("Введено ", len(my_string), " символов." )
print(my_string.upper())
print(my_string.lower())
print(my_string.replace(" ",""))
print(my_string[0])
print(my_string[-1])
